# title of website
title: Example site

# description of website
description: Site description

# your website url
url: "https://example.com"

# github profile url
github: "https://github.com/x1ah"

# footer message
footer: © 2017-2020 WebStack design by Viggo

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

google_analytics: "G-EXE1PJ8CR2"

content:
  categories:
    - name: 社区
      sites:
        - name: V2EX
          description: 创意工作者的社区。
          url: https://v2ex.com

        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/
        - name: 36kr
          description: 创业资讯、科技新闻
          url: https://36kr.com/

    - name: 图标素材
      sites:
        - name: iconfont
          description: 阿里巴巴矢量图标库
          url: https://www.iconfont.cn/

        - name: iconfinder
          description: 2,100,000+ free and premium vector icons.
          url: https://www.iconfinder.com/
